### ISSUE TITLE
The parser chokes on `1.5dppx`

### ISSUE THREAD

**Issue by nex3** [shellscape/postcss-values-parser#104]
* Operating System (or Browser): RunKit
* Node Version: 10.18.0
* postcss-values-parser Version: 3.1.1

### How Do We Reproduce?

https://runkit.com/nex3/5e446258c092240013ead2f1

```js
const pvp = require('postcss-values-parser')
pvp.parse("1.5dppx")
```

### Expected Behavior

I expect this to parse as a `Numeric`.

I chose to highlight `dppx` here because it's [a specified unit](https://drafts.csswg.org/css-values-4/#resolution), but this will reproduce with any unit string postcss-values-parser doesn't [explicitly recognize](https://github.com/shellscape/postcss-values-parser/blob/fcfe128f3a1cb07151ca53a370eb6cee8a314ebd/lib/nodes/Numeric.js#L17). I would more broadly expect anything matching [`<dimension-token>`](https://drafts.csswg.org/css-syntax-3/#ref-for-typedef-dimension-token%E2%91%A2) to parse as a `Numeric`, even if its unit isn't specified yet. This is more future-proof as the specification evolves, and more friendly to postprocessors that may define their own custom units.

### Actual Behavior

It throws a `CssSyntaxError`.

**Comment by shellscape** [comment]
Fixed in #109
