### ISSUE TITLE
Exception thrown on float angle values

### ISSUE THREAD

**Issue by lazd** [shellscape/postcss-values-parser#106]
- Operating System (or Browser): macOS
- Node Version: v13.3.0
- postcss-values-parser Version: 3.11

### How Do We Reproduce?

https://repl.it/@lazd/postcss-values-parser-float-angle-values

### Expected Behavior

`parse(.5deg)` and `parse(1.5deg)` and friends do not throw. See [W3 spec] for all possible angle values https://www.w3.org/TR/css-values-4/#angles.

### Actual Behavior

`parse(.5deg)` and `parse(1.5deg)` throw `<css input>:1:1: Unknown word`

**Comment by lazd** [comment]
Related to #76. Big ups to @bartveneman for the repl.it that made it easy to demonstrate the issue.

**Comment by nex3** [comment]
See also https://github.com/shellscape/postcss-values-parser/issues/104.

**Comment by shellscape** [comment]
Fixed in #109

**Comment by bartveneman** [comment]
Wow, thanks so much @jonathantneal for implementing! 🥳
