### ISSUE TITLE
Sass forward prefixes parsing as a word and operator instead of just a word

### ISSUE THREAD

**Issue by wegry** [shellscape/postcss-values-parser#108]
- Operating System (or Browser):
macOS 10.15.4

- Node Version:
12.16.1

- postcss-values-parser Version:
2.0.1

### How Do We Reproduce?
```scss
@forward "src/list" as list-*;
```

is being parsed as 

```json
{
  "raws": {
    "before": "",
    "after": ""
  },
  "type": "value-root",
  "group": {
    "raws": {
      "before": "",
      "after": ""
    },
    "type": "value-value",
    "unbalanced": 0,
    "group": {
      "groups": [
        {
          "raws": {
            "before": "",
            "after": "",
            "quote": "\""
          },
          "value": "src/list",
          "source": {
            "start": {
              "line": 1,
              "column": 1
            },
            "end": {
              "line": 1,
              "column": 10
            }
          },
          "sourceIndex": 0,
          "quoted": true,
          "type": "value-string"
        },
        {
          "raws": {
            "before": " ",
            "after": ""
          },
          "value": "as",
          "source": {
            "start": {
              "line": 1,
              "column": 12
            },
            "end": {
              "line": 1,
              "column": 13
            }
          },
          "sourceIndex": 11,
          "type": "value-word",
          "isHex": false,
          "isColor": false
        },
        {
          "raws": {
            "before": " ",
            "after": ""
          },
          "value": "list-",
          "source": {
            "start": {
              "line": 1,
              "column": 15
            },
            "end": {
              "line": 1,
              "column": 19
            }
          },
          "sourceIndex": 14,
          "type": "value-word",
          "isHex": false,
          "isColor": false
        },
        {
          "raws": {
            "before": "",
            "after": ""
          },
          "value": "*",
          "source": {
            "start": {
              "line": 1,
              "column": 20
            },
            "end": {
              "line": 1,
              "column": 20
            }
          },
          "sourceIndex": 1,
          "type": "value-operator"
        }
      ],
      "type": "value-comma_group"
    }
  }
}
```

### Expected Behavior

I'm jousting with https://github.com/prettier/prettier/issues/7019. [Sass @forward prefixes](https://sass-lang.com/documentation/at-rules/forward#adding-a-prefix) are tough. I've already stopped by [postcss-scss](https://github.com/postcss/postcss-scss/issues/103#issuecomment-612517540) with the same concern.

`*` should be part of the preceding value-word node `list-`. 

### Actual Behavior

`*` isn't part of the preceding value-word node `list-`.

**Comment by shellscape** [comment]
Have a link to the spec for that one by chance?

**Comment by wegry** [comment]
@shellscape https://github.com/sass/sass-spec/blob/master/spec/directives/forward/member/as.hrx might help? It’s test cases for the reference implementation.

**Comment by shellscape** [comment]
Thanks. This package isn't a sass parser. If it's not in the css spec, were unlikely to support it.

**Comment by michaelfaith** [comment]
@wegry is this issue being resolved?  This is causing a big problem for us.  Is there a way to turn this off?

**Comment by wegry** [comment]
@michaelfaith I've been out of this stack since I created this (Angular 11), but I vaguely recall that we had issues with a parser. 

What sort of issue are you having and what versions of the associated libraries are you using?

**Comment by michaelfaith** [comment]
@wegry yeah I followed the trail over from the Prettier issue you referenced: https://github.com/prettier/prettier/issues/7019
Where it's messing up @forward statements, separating the * out.
e.g.
```
// Before: 
@forward 'src/list' as list-*;

// After: 
@forward 'src/list' as list- *;
```

Dealing with this in Angular 12, Prettier 2.4.0 which appears to use 2.0.1 of this library.

**Comment by wegry** [comment]
@michaelfaith if you're willing to just kick the can down the road a bit:

```scss
// prettier-ignore
@forward 'src/list' as list-*;
```

[This prettier playground shows it in action with latest](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSgAEAzGgdwEMcATDAcgGccYVABtC-GLwzt+GMRNIAqANwgANCAhYi0fslCccEVgAVOCPSnYiOATz0aARjnZgA1vgDK7ALZwAMoRQcMhM1vxwTi7uXliuQRTIMDgArpEgcD6OcFxcOf7sUBQp7BRwAGI0PuwECcgg7CkwEOogABYwPiIA6m2E8PxxYHCeFv2EAG79tvVg-A4gQRE4MCYuFNWh4ekAVvwAHp4JInAAiikQ8FsiERpxOMv1-HMLuEEw3YRcMG3IABwABjuRgi3RcWHquDgywmIQ0AEcLvA1lpLA1+KRgjkcq08IjCHg1qVNkgwjd0hEfIQkqkKcczkiQqTthoYOxHJ9vr8kAAmVkuQhiIoAYQgPhJGX4AFZWikIgAVdmWMm3EATNIASSgeVgnjAOEI2gAgtrPDBbCdrhEAL7WoA).

**Comment by michaelfaith** [comment]
@wegry right on. I can go with that until there's a fix in, which i guess will need to come in the form of a new sass parser on the Prettier side. Appreciate the recommendation.
