### ISSUE TITLE
License Change: from MPL-2.0 to MIT to be aligned with postcss pkgs

### ISSUE THREAD

**Issue by shadiabuhilal** [shellscape/postcss-values-parser#115]
### Expected Behavior / Situation
MIT License

### Actual Behavior / Situation
MPL-2.0 License

### Modification Proposal
Some companies  don't allow MPL-2.0 License, also all postcss pkgs are MIT License.
Please try to align with postcss Licenses.

**Comment by shellscape** [comment]
Thanks for the suggestion. Unfortunately I won't be changing the licensing.
