### ISSUE TITLE
Should parens be part of raws

### ISSUE THREAD

**Issue by jonathantneal** [shellscape/postcss-values-parser#13]
Looking over the API, this example struck me as including unnecessary work.

```js
let func = parser.func({ value: 'calc' });

func.append(parser.paren());
func.append(parser.paren({ value: ')' }));

func.toString();
// → calc()
```

Should parens be raws? Otherwise, a stringified function without parens would be re-parsed as a word, right?

This seems like unnecessary work on the part of devs. It would be like PostCSS requiring curly braces within at-rules and rules.

```js
let rule = postcss.rule({ selector: 'body' });

rule.append(parser.brace());
rule.append(parser.brace({ value: '}' }));

rule.toString();
// → .body{}
```

By either including the whitespace around the parens or making them separate raws, would that preserve formatting? Sorry in advance if I misunderstand something.

**Comment by shellscape** [comment]
Do you have a link to PostCSS docs that outline how it works on their end? I'd welcome a PR that provided an alternative.

**Comment by jonathantneal** [comment]
Yes, we have two forms of documentation.

First, [CSS Values and Units Module Level 3: Functional Notations](https://www.w3.org/TR/css3-values/#functional-notations).

> The syntax starts with the name of the function immediately followed by a left parenthesis... followed by the argument(s) to the notation followed by a right parenthesis. White space is allowed, but optional, immediately inside the parentheses.

Second, [PostCSS `stringifier.es6`](https://github.com/postcss/postcss/blob/master/lib/stringifier.es6#L90-L104). PostCSS Rules preserve the raws around braces and re-introduce them with the stringifier.

```js
this.builder(start + between + '{', node, 'start');

...

this.builder('}', node, 'end');
```

**Comment by shellscape** [comment]
The first implication that this will have is to Lesshint, as it uses the Paren nodes to apply rules there. I need to look at how that's going to be affected first and foremost. The second implication would be to parsing if we were to take Parens out of the node tree and put them into raws. My guess is that the tokenizer could remain the same but that the parser consuming the token array would have to be updated. I think that's a reasonable change to remove the extra work of constructing a function, but I'd need to see how other things would be impacted along the way.

**Comment by shellscape** [comment]
@jonathantneal I'm gonna close this purely for organizational means. if you'd like to reopen it, please do let me know.
