### ISSUE TITLE
No comment in property value

### ISSUE THREAD

**Issue by strarsis** [shellscape/postcss-values-parser#131]
- Operating System (or Browser): WSL 2
- Node Version: v14.16.0
- postcss-values-parser Version: 5.0.0

### How Do We Reproduce?
1. Use the following input styles:
```css
.test {
  background: /*test*/ red;
}
````
This is valid CSS. The `background` property contains a comment in its value.

### Expected Behavior
Comment nodes are parsed out.

### Actual Behavior
No comment nodes.

**Comment by shellscape** [comment]
would gladly accept a pull request to resolve this issue

**Comment by strarsis** [comment]
So after some testing I came to the conclusion that not this parser skips comments but this is rather something in PostCSS (Declaration node).
