### ISSUE TITLE
Cannot parse calculations without spaces around the * operator

### ISSUE THREAD

**Issue by stof** [shellscape/postcss-values-parser#138]
- Operating System (or Browser): Ubuntu
- Node Version: 14.17.6
- postcss-values-parser Version: 2.0.1

### How Do We Reproduce?

Parse the value `calc(var(--bs-gutter-y)*-1)`

### Expected Behavior

Parsing is successful

### Actual Behavior

A ParserError is reported.

Note that this comes from the issue reported at https://github.com/sass/dart-sass/issues/1496. Newer versions of sass produce this value in compressed mode when compiling the sass code of Bootstrap 5. Older versions were putting spaces around the `*` operator, but they are optional in CSS for the `*` and `/` operators.

**Comment by stof** [comment]
Looking at it, this version is far outdated. But it is the version used (transitively) by `postcss-preset-env`, which is used in create-react-app

**Comment by tagliala** [comment]
This package is also transitively used by [Webpacker](https://github.com/rails/webpacker) 5, so at the moment it is not possible to compile Bootstrap with `NODE_ENV=production`

**Comment by shellscape** [comment]
PRs are welcome

**Comment by liujingbreak** [comment]
Same issue of mine on **postcss-values-parser@2.0.1**, it is due to the parser logic does not cover case of "nagetive number" as a valid word, and there is no branch for v2.0.1, need a new branch on tag 2.0.1 to fix.

```
ERROR in ./node_modules/@material/layout-grid/mdc-layout-grid.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 52
calc(var(--mdc-layout-grid-gutter-desktop, 24px)/2*-1)

at /Users/liujing/bk/plink/react-space/node_modules/@material/layout-grid/mdc-layout-grid.scss:1:932
    at Parser.error (/Users/liujing/bk/plink/react-space/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/Users/liujing/bk/plink/react-space/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (/Users/liujing/bk/plink/react-space/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/Users/liujing/bk/plink/react-space/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/Users/liujing/bk/plink/react-space/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/Users/liujing/bk/plink/react-space/node_modules/postcss-custom-properties/src/lib/postcss-values-parser.js:4:29)
    at callback (/Users/liujing/bk/plink/react-space/node_modules/postcss-custom-properties/src/lib/transform-properties.js:11:21)
```

`-` is preceded by `*` in `calc()` function, then this issue happens.

<img width="834" alt="Screen Shot 2021-11-19 at 2 43 24 PM" src="https://user-images.githubusercontent.com/3509180/142577451-01196c01-6fe2-4627-9727-7b01ec4837ea.png">

**Comment by jeffbax** [comment]
I don't quite have a sample available as I'm not great at debugging this type of issue (will try more in a bit), but I'm seeing something similar to @tagliala having recently updated Webpacker in my project -- except in theory for the `-` character surfacing:

```
Syntax Error
[ 'operator', '-', 1, 25, 1, 26, 24 ]
```

when I add some crude logging to `postcss-values-parser/lib/parser.js` within `error (message, token)`
