### ISSUE TITLE
Multiple versions of this library can't coexist

### ISSUE THREAD

**Issue by Antonio-Laguna** [shellscape/postcss-values-parser#143]
- Operating System (or Browser): macOS
- Node Version: 14.17.6
- postcss-values-parser Version: 6.0.1

### How Do We Reproduce?

After this bug surfaced https://github.com/csstools/postcss-preset-env/issues/225 we started to investigate what could be causing it given that it works locally but fails within postcss-preset-env@7.0.0 

We've realised that `registerWalker` is modifying the prototype of Container which means that if you have multiple versions of this package running you're in for a bad time.

The registering happens here: https://github.com/shellscape/postcss-values-parser/blob/0357c82dad24db2f1babc68be4f4aa065a3209a4/lib/walker.js#L27 which runs multiple times (once per version) while https://github.com/shellscape/postcss-values-parser/blob/0357c82dad24db2f1babc68be4f4aa065a3209a4/lib/walker.js#L43 makes it so `node` is only an instance of type for the first `postcss-values-parser` that does it's registering which makes this non-deterministic and kind-of dangerous if multiple instances coexist.

### Expected Behavior

Should be possible to have different versions without them interfering.

### Actual Behavior

It's not possible to do that.

I understand that this is not a trivial change and I'm happy to contribute time and/or to discuss anything.

**Comment by shellscape** [comment]
I'd be happy to review a PR to resolve this. The package has been up and relatively stable for a number of years, so I don't have a lot of personal motivation to dive into this one.

**Comment by shellscape** [comment]
This is resolved in the `major/css-tree` branch, which will be released as v7
