### ISSUE TITLE
Flat parsing of "(foo,bar),(baz)"

### ISSUE THREAD

**Issue by edg2s** [shellscape/postcss-values-parser#21]
This gets parsed as a completely flat AST. It seems to me like the parentheses groups should be represented as nodes. postcss-value-parser interprets them as functions with no names so it would make sense to be consistent with that. I am trying to rewrite stylelint to use this parser instead of value-parser, and this is a requirement for certain rules.

**Comment by shellscape** [comment]
What's the use case for that type of value? `value-parser` isn't very opinionated, whereas this module is. so valid use-cases for values said not to be parsing correctly are a necessity.

**Comment by edg2s** [comment]
The first case I've come across it's used to detect scss lists, so `$color: ( white: #fff, red: #f00 );`. This probably isn't the best example, but letting the user traverse balanced brackets in expressions seems useful in general.

**Comment by shellscape** [comment]
well see, in the css spec that's not valid. that's a css-like variant, and it's tough to be opinionated for folks who want to use this for postcss and also those who want to use it for css-like variants. It's hard to differentiate between a function in valid css and a paren grouping. This will have to expand the `loose` option and assume a paren pairing when there's no function name. I'd welcome a PR but this isn't something that I'm going to be able to get to for some time.

**Comment by edg2s** [comment]
My understanding of the readme was that this parser was originally created for LESS linting, which is a CSS-like variant?

**Comment by shellscape** [comment]
It was, but if you're extrapolating that to mean that it's a values parser for css-like languages first, then you're making a poor assumption. There's an entire section dedicated to [CSS-Like Languages](https://github.com/lesshint/postcss-values-parser#css-like-languages) directly below that intro.

**Comment by edg2s** [comment]
Agreed - I think aiming for detailed support of all css-like languages would be foolish - but I think some generic parenthesis parsing would be generally useful for a loose mode and help with cases like this and #23

**Comment by shellscape** [comment]
Paren grouping (where a group is a parent Node) makes for a very complex tree, and I don't see the need for adding that complexity to the tree. But if the parser needs a `loose` mode modification to support a paren grouping like that, then I'm open to it.

**Comment by shellscape** [comment]
Closing due to age. If anyone would like to open a PR for this we can continue the discussion there.
