### ISSUE TITLE
return false in Node#walk aborts the entire walk

### ISSUE THREAD

**Issue by edg2s** [shellscape/postcss-values-parser#22]
Is there a clean way to stop a walk from descending any further, but to continue to the next sibling? In `postcss-value-parser` this is done by returning false, in here that would abandon the whole walk.

Consider a rule that is looking for offset values in `background: url(foo.jpg) 3px 5px;`. When I come across the FunctionNode for `url` I want to stop descending, but I still want to iterate over the siblings where the offsets are. My current approach is to set `node.walk=null` then return undefined, but this is very hacky.

**Comment by shellscape** [comment]
What's the use case? eg. Why would one want to do this?

**Comment by edg2s** [comment]
Perhaps I was not clear enough with my example. Consider a rule that is linting the case of keywords, such that they must be lower-case, then I want to examine:

`background: url(ToP) TOP left`

As soon as I seen the url function I want to stop descending as I don't care the 'ToP' isn't lowercase - however I want to continue parsing the siblings, so I detect 'TOP' as being the wrong case.

**Comment by edg2s** [comment]
If I wrote a patch to change `return false` to mean "abandon this branch" as opposed to "abandon the whole tree" would that be acceptable? Or would it cause too many regressions in downstream use?

**Comment by shellscape** [comment]
That's probably a good start, but returning an object with properties to instruct the walker on what course of action to take would probably be more extensible down the road. eg: `return { end: 'tree' };` or `return { end: 'branch' }` or some such.

**Comment by shellscape** [comment]
Closing due to age. If anyone would like to open a PR for this we can continue the discussion there.
