### ISSUE TITLE
SASS Interpolation Not Parsed in Loose Mode

### ISSUE THREAD

**Issue by edg2s** [shellscape/postcss-values-parser#23]
* Node Version: 7.6
* NPM Version: 4.1.2
* postcss-values-parser Version: latest

This issue is regarding a problem with:
- [ ] Standard CSS
- [ ] LESS
- [x] SCSS
- [x] SASS

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```css
a { margin: calc(100% - #{$margin * 2px}); }
```

```
// resulting node tree
func calc
  paren
  number 100, unit='%'
  operator '-'
  word '#{$margin'
  operator '*'
  number 2, unit='px}'
  paren
```

### Expected Behavior
The parser should account for the SCSS bracket interpolation.

### Actual Behavior
SCSS bracket interpolation isn't recognized and is instead part of surrounding word nodes. See tree output.

### How can we reproduce the behavior?
Parse the references css with `loose: true` option.

**Comment by shellscape** [comment]
Right, again, that's not valid CSS. If that's something that needs to be supported for SCSS, then you'll need to expand the `loose` option.

I welcome your contributions - I really do, and they're appreciated. But please, for all that is holy, please start listing technical information. It's never been acceptable for any project on Github to use "tripped up" in place of pasting the actual error generated. I haven't put together Issue and PR templates because they haven't been needed, but you've left out key info on three issues now.

**Comment by edg2s** [comment]
Sorry, I thought it was obvious that 'px}' would be problematic. Consider a linting rule that blacklists or whitelists css units by strict string equality. Say I have a whitelist that includes 'px', then this number will still not match that whitelist as 'px}' !== 'px'.

**Comment by shellscape** [comment]
I don't think you're understanding when I say that `#{ ... }` within a value isn't valid CSS. It's not going to be parsed special because the parser doesn't know it's special - it's for a css variant, and that needs to be taken into account in some way. At present we use the `loose` option to denote that the entity doing the parsing is expecting a css-like variant/language. What you left out is that the value of the node for the unit is `px}` instead of just `px`, which makes total sense considering the info above and how the parser tokenizes.

The tokenizer and/or parser will have to be extended to treat that `#{ ... }` block differently.

**Comment by edg2s** [comment]
Have you considered adopting a welcoming attitude to new contributors, like the guys at stylelint? I'm pretty thick skinned, but others would be put off by such aggressive questioning. I'm don't expect you drop everything and write code for the issues I'm filing - or even accept that they are good ideas, but a civil discussion would be a start.

> What you left out is that the value of the node for the unit is px} instead of just px

?? It was in the example AST and referenced immediately after: "The curly bracket in the unit..."

> I don't think you're understanding when I say that #{ ... } within a value isn't valid CSS. It's not going to be parsed special because the parser doesn't know it's special

At no point have I not fully understood that the problem here is extended CSS syntax not being recognised by a parser mainly written for pure CSS, I'm not sure where you got that impression.
Given the parser has an explicit mode for use with extended syntax, and that it works fairly well with them (but for these few edge case) I though filing issues about said edge cases would be appreciated, so they can be documented, and at some point someone may attempt to fix them.

**Comment by shellscape** [comment]
unconstructive comment has been removed. if you'd like to continue to work through the issue you reported, that is welcome.

**Comment by edg2s** [comment]
I'd love to, but perhaps while you're editing comments you could remove the parts where you accuse me of not understanding something I clearly do (that `#{...}` is SASS, not valid CSS), or not doing something I've clearly done ("you left out is that the value of the node for the unit is `px}`) as a sign of good faith?

**Comment by kokarn** [comment]
Woah, this got very ugly very fast.

I don't like that we are removing comments, even if we don't agree with them.
I think we should welcome issues with languages, even tho they are not currently supported. We could always keep them open in case somebody at a later stage finds the time to implement support for SCSS.

@shellscape If you feel you get very aggravated by a post, just let it be and let @jwilsson handle it.

**Comment by shellscape** [comment]
@kokarn this repo is under the lesshint org but I still maintain ownership.

**Comment by kokarn** [comment]
Okay, so let's just let me get this clear.

You feel this repository is 100% yours and you can do whatever you feel like with no regards to the rest of the org?

**Comment by shellscape** [comment]
@edg2s revisiting this; what kind of node structure would you find reasonable for handling interpolation bracket pairs? would this require a new node type?

**Comment by shellscape** [comment]
decided to go with a word-based solution here. That interpolation is pretty specific to SCSS, so those special characters are now tokenized and treated as separate words when outside strings, etc.

Here's sample tokenizer output:

```js
[ [ 'word', 'calc', 1, 1, 1, 4, 0 ],
  [ '(', '(', 1, 5, 1, 4, 4 ],
  [ 'word', '100%', 1, 6, 1, 9, 5 ],
  [ 'space', ' ', 1, 10, 1, 11, 9 ],
  [ 'operator', '-', 1, 11, 1, 12, 10 ],
  [ 'space', ' ', 1, 12, 1, 13, 11 ],
  [ '#', '#', 1, 13, 1, 13, 12 ],
  [ '{', '{', 1, 14, 1, 13, 13 ],
  [ 'word', '$margin', 1, 15, 1, 21, 14 ],
  [ 'space', ' ', 1, 22, 1, 23, 21 ],
  [ 'operator', '*', 1, 23, 1, 24, 22 ],
  [ 'space', ' ', 1, 24, 1, 25, 23 ],
  [ 'word', '2px', 1, 25, 1, 27, 24 ],
  [ '}', '}', 1, 28, 1, 27, 27 ],
  [ ')', ')', 1, 29, 1, 27, 28 ] ]
```

and here's what the tests for it look like:

```js
    {
      it: 'should parse calc function with scss interpolation #23',
      test: 'calc(100% - #{$margin * 2px})',
      expected: [
        { type: 'func', value: 'calc' },
        { type: 'paren', value: '(' },
        { type: 'number', value: '100', unit: '%' },
        { type: 'operator', value: '-' },
        { type: 'word', value: '#' },
        { type: 'word', value: '{' },
        { type: 'word', value: '$margin' },
        { type: 'operator', value: '*' },
        { type: 'number', value: '2', unit: 'px' },
        { type: 'word', value: '}' },
        { type: 'paren', value: ')' }
      ]
    }
```
