### ISSUE TITLE
Parse Error parsing dash in `calc(-0.5 * var(ei-table-cell-padding));`

### ISSUE THREAD

**Issue by vjeux** [shellscape/postcss-values-parser#29]
* Node Version: 4.3.2
* NPM Version: 3.10.10
* postcss-values-parser Version: 1.2.2

This issue is regarding a problem with:
- [x] Standard CSS

```css
calc(-0.5 * var(ei-table-cell-padding))
```

```
{ [ParserError: Syntax Error at line: 1, column 6] name: 'ParserError' }
```

### Expected Behavior
Not to error on the `-`

### Actual Behavior
Errors

### How can we reproduce the behavior?
Just parse this block of code

**Comment by vjeux** [comment]
For context, I'm running this through the entire Facebook codebase. There are only a handful of errors, I'm working on categorizing them right now :)

**Comment by vjeux** [comment]
```js
-moz-calc(100% - 320px)
```

is also throwing on the middle `-`

**Comment by vjeux** [comment]
Also an issue for `+`: `-webkit-calc(100% + 20px)`

**Comment by shellscape** [comment]
Oof. The whole operators thing per spec was tricky to implement, and I was wondering if/when it was going to start causing other headaches. For poops and giggles, try running that with the `loose: true` option. If that doesn't solve it, this is going to be not fun to fix :)

**Comment by vjeux** [comment]
Those are the only two things that are crashing and only for ~10 files out of the entire codebase, so it's definitely an edge case :)

**Comment by vjeux** [comment]
I'll try the loose mode and report back

**Comment by vjeux** [comment]
Omg, loose mode is working! Thanks :)

**Comment by shellscape** [comment]
Cool, that should get you by in the meantime, but that's still a bug. It's throwing on the `-0.5` which should be valid there.
