### ISSUE TITLE
Word.isColor doesn't support RGBA hex colors

### ISSUE THREAD

**Issue by jwilsson** [shellscape/postcss-values-parser#32]
* Node Version: `6.11.1`
* NPM Version: `5.3.0`
* postcss-values-parser Version: `1.2.2`

This issue is regarding a problem with:
- [x] Standard CSS
- [ ] LESS
- [ ] SCSS
- [ ] SASS

**For example:**
```css
color: #000000ff;
```

### Expected Behavior
`Word.isColor` should be `true`.

### Actual Behavior
`Word.isColor` is `false`.

### How can we reproduce the behavior?
Run the parser on a RGBA hex color, for example the one above.

This should be a simple extension of the current `isColor` regex, to allow for colors with 8 chars. I'd be happy to do it.

**Comment by shellscape** [comment]
🍺 https://github.com/shellscape/postcss-values-parser/blob/master/lib/parser.js#L466
