### ISSUE TITLE
Add markdown-toc to API docs please

### ISSUE THREAD

**Issue by corysimmons** [shellscape/postcss-values-parser#35]
https://github.com/jonschlinkert/markdown-toc would make https://github.com/shellscape/postcss-values-parser/blob/master/API.md much easier to explore.

**Comment by shellscape** [comment]
We'd be happy to accept a PR for that.

**Comment by corysimmons** [comment]
I can do that. 👍 
Thanks for this awesome tool btw. So easy... 🤤

**Comment by shellscape** [comment]
@corysimmons last ping before I close as abandoned 😃

**Comment by corysimmons** [comment]
https://github.com/shellscape/postcss-values-parser/pull/39

ha, sorry, forgot. PR'd.
