### ISSUE TITLE
SCSS Interpolation in strings

### ISSUE THREAD

**Issue by lydell** [shellscape/postcss-values-parser#37]
* Node Version: 8.3.0
* NPM Version: 5.3.0
* postcss-values-parser Version: 1.3.0

This issue is regarding a problem with:
- [ ] Standard CSS
- [ ] LESS
- [x] SCSS
- [ ] SASS

```scss
"a #{"1"} b #{2} c"
```

### Actual Behavior

Parsed as:

```
StringNode {
  value: 'a #{'
}
NumberNode {
  value: '1'
}
StringNode {
  value: '} b #{2} c'
}
```

### Expected Behavior

Proposal:

Similar to how Babylon parses template literals in JavaScript: [astexplorer](https://astexplorer.net/#/gist/39615fad145f528a71f8eacbf25a5273/74150d993851fa94eea30cf643551961bf04676e)

Something like this:

```
InterpolationStringNode {
  expressions: [
    StringNode {
      value: '1'
    },
    NumberNode {
      value: '2'
    }
  ],
  quasis: [
    InterpolationStringElementNode {
      value: 'a '
    },
    InterpolationStringElementNode {
      value: ' b '
    },
    InterpolationStringElementNode {
      value: ' c'
    }
  ]
}
```

(The "expressions" and "quasis" names comes from Babylon’s AST. I made up "InterpolationStringNode". I don’t care about what they’re called.)

When you encounter `#{` in a string

1. Push the string so far to `quasis`
2. Recursively parse with postcss-values-parser until the next unbalanced `}`. (Error handling, if no ending `}` is found throw `TokenizeError: Unclosed interpolation` or something.)
3. Start to parse as a string again (until the end quote or the next `#{`).

Notes:

- Interpolations can contain any expression, even another string with
  interpolations (recursively).
- It is possible to escape interpolations: `"\#{1}"` is a single `StringNode`.

### How can we reproduce the behavior?

```js
const parse = require("postcss-values-parser")

const test = '"a #{"1"} b #{2} c"'
const ast = parse(test, {loose: true}).parse()

console.dir(ast, {colors: true, depth: null})
```

### Related

- #23 
- prettier/prettier#2734

**Comment by shellscape** [comment]
I'd go with `InterpolationNode` and put `InterpolationElementNode` under its child nodes. A property for tracking the type of interpolation, or format (`#{..}` etc) would be desirable. A proper implementation would support interpolation in LESS and SCSS.

**Comment by lydell** [comment]
Sounds good! Just a quick note: As far as I know, Less only supports simple variable interpolations of the form `@{variable-name}` (interpolating expressions is not supported).

**Comment by shellscape** [comment]
@lydell are you interested in submitting a PR for this?

**Comment by lydell** [comment]
No, I'm not. I wish I was, though.

**Comment by shellscape** [comment]
Happy to report that the offending css value passes in the `next` branch. This is accomplished for SCSS by using the options for the parser:

```js
const options = {
  interpolation: { prefix: '#' }
};
const root = parse('a #{"1"} b #{2} c', options);
```

I'll be releasing a beta of 3.0.0 later today. Thanks for reporting the issue. Cheers 🍻
