### ISSUE TITLE
Should parentheses have child nodes?

### ISSUE THREAD

**Issue by jonathantneal** [shellscape/postcss-values-parser#41]
* Node Version: 9.3.0
* NPM Version: 5.6.0
* postcss-values-parser Version: 1.3.1

This issue is regarding a problem with:
- [X] Standard CSS

### Description

I was expecting parentheses to group a portion of the following CSS value, but they do not:

```
5px / (2px + 3px)
```

The result, expressed as a simplified array, demonstrate the grouping as:

```js
[
  '5px',
  '/',
  '(',
  '2px',
  '+',
  '3px',
  ')'
]
```

Whereas I would have expected:

```js
[
  '5px',
  '/'
  [
    '2px',
    '3px'
  ]
]
```

So, would you categorize this as a feature request, or would you deliberately wish to *not* group nodes by parentheses? Or something else?

### Expected Behavior

I was expecting a **Parentheses** container node.

### Actual Behavior

The parenthesis is treated more like an operator.

### How can we reproduce the behavior?

```
require('postcss-values-parser')('5px / (2px + 3px)').parse();
```

**Comment by shellscape** [comment]
I'm not opposed to this in any sense. But for the purpose of identifying broken paren groupings and stringifying, it was far simpler to keep the status quo from `postcss-value-parser`. I had attempted to do just that in the past, when I was first working on the module, but ran into edge cases each time I thought I had it solved. (I can't recall what those were anymore, but recall my frustration) I'd be more than open to this change provided it had some thorough testing around it.
