### ISSUE TITLE
Allow custom parse element as `value-word`

### ISSUE THREAD

**Issue by evilebottnawi** [shellscape/postcss-values-parser#42]
* Node Version: latest
* NPM Version: latest
* postcss-values-parser Version: latest

This issue is regarding a problem with:
- [ ] Standard CSS
- [ ] LESS
- [x] SCSS
- [x] SASS

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```scss
$i: 1px;
a {
  color: $i>0;
}
```

For `prettier`

### Expected Behavior

Allow to parse custom words as `value-word`. Example pass `$i>0` should output 

```shell
[ Word {
           raws: [Object],
           value: '$i',
           source: [Object],
           sourceIndex: 0,
           type: 'word',
           isHex: false,
           isColor: false },
         Word {
           raws: [Object],
           value: '>',
           source: [Object],
           sourceIndex: 3,
           type: 'word',
           isHex: false,
           isColor: false },
         NumberNode {
           raws: [Object],
           value: '0',
           source: [Object],
           sourceIndex: 5,
           unit: '',
           type: 'number' } ],
```

Why? We use `postcss-values-parser` for parsing control structure (example `@while`) and this would allow us to better formatting the output.

### Actual Behavior

Right now we get `$i>0` as one `value-word`

### How can we reproduce the behavior?

Example above

I can do PR and tests.

**Comment by shellscape** [comment]
What would the benefit of this being in values-parser be versus a regular expression for this value kind?

Can these expressions be nested within one-another?

**Comment by evilebottnawi** [comment]
@shellscape Print spaces between operators (`==`, `!=`, `>`, `<`, `<=`, `>=`) in control directives:
Input:
```scss
@while $i>0{}
```
Output:
```scss
@while $i > 0{}
```

No they are not be nested.
