### ISSUE TITLE
Remove atword in favor `word` in next major

### ISSUE THREAD

**Issue by evilebottnawi** [shellscape/postcss-values-parser#48]
* Node Version: latest
* NPM Version: latest
* postcss-values-parser Version: latest

This issue is regarding a problem with:
- [ ] Standard CSS
- [x] LESS
- [x] SCSS
- [x] SASS

### Expected Behavior

Less variable should be interpreted as `word`, for sass/less/custom-variables we use logic as `word`. Maybe add some logic to detect is variable(sass/scss/less/custom-variable) or not. Export this detection as property `word` node.

### Actual Behavior

As `atword`.

### How can we reproduce the behavior?

`@value`

**Comment by shellscape** [comment]
I think that will introduce too much extra logic and be too fragile to maintain. I would however, be open to exporting utils that contained a function which would contain the logic to determine if an `AtWord` was a `Word` for special cases. Users would have to run that util function when receiving an AST.

Would that be acceptable?

**Comment by evilebottnawi** [comment]
@shellscape We can avoid detection variable here. It is just purpose. Yes `utils` for this are acceptable :+1: 

Just a suggestion parse `atword` as `word` in next major.
