### ISSUE TITLE
All walk functions registered with registerWalker do not work

### ISSUE THREAD

**Issue by nuintun** [shellscape/postcss-values-parser#50]
* Node Version: 9.8.0
* NPM Version: 5.6.0
* postcss-values-parser Version: 1.4.0

This issue is regarding a problem with:
- [x] Standard CSS
- [ ] LESS
- [ ] SCSS
- [ ] SASS

All walk functions `(eg: walkFunctionNodes, walkComments)` registered with `registerWalker` do not work.

**Comment by shellscape** [comment]
False

**Comment by nuintun** [comment]
@shellscape  Try this

```js
const source = '/*1*/ 5px /* 2 */';
const ast = new Parser(source).parse();

ast.first.walkComments(node => {
  console.log(node.value);
});
```

[RunKit Example](https://runkit.com/nuintun/5aa88196d8f9eb0012694398)
