### ISSUE TITLE
node.isColor does not support rgb(a), hsl(a) and color keywords

### ISSUE THREAD

**Issue by bartveneman** [shellscape/postcss-values-parser#64]
### Feature Use Case
For convenience and accuracy it would be nice if `node.isColor` would also recognize `hsl()`, `hsla()`, `rgb()`, `rgba()` and color keyword (`blue`, `yellow`) nodes. 

### Feature Proposal
For [@projectwallace/css-analyzer](https://github.com/projectwallace/css-analyzer) I use [this logic](https://github.com/projectwallace/css-analyzer/blob/a1c3dfe3885605c7e8b0226e62d67e2d1f4725ee/src/analyzer/values/colors.js#L41) to determine whether a node is a color.

**Comment by shellscape** [comment]
Absolutely.

_In the future please _do_ use the issue templates._

**Comment by bartveneman** [comment]
*updated opening comment*

**Comment by shellscape** [comment]
Added in 7108d9a. I'll release a new beta shortly.

**Comment by bartveneman** [comment]
Whoa, that’s quick!
