### ISSUE TITLE
Stringifier Ignores Manually Added Func Child Nodes

### ISSUE THREAD

**Issue by jonathantneal** [shellscape/postcss-values-parser#69]
- Webpack Version: N/A
- Operating System (or Browser): N/A
- Node Version: N/A
- postcss-values-parser Version: 3.0.1

### How Do We Reproduce?

Insert a new node into an AST.

```mjs
import valuesParser from 'postcss-values-parser';
import Punctuation from 'postcss-values-parser/lib/nodes/Punctuation';

const astValue = valuesParser.parse('rgb(100% 100% 100%)');

astValue.nodes[0].nodes.splice(1, 0, new Punctuation({ value: ',' }));
astValue.nodes[0].nodes.splice(2, 0, new Punctuation({ value: ',' }));

console.log({
	punctuation: valuesParser.nodeToString(astValue.nodes[0].nodes[1]),
	root: valuesParser.nodeToString(astValue)
});
```

### Expected Behavior

Commas are added.

```js
{
  punctuation: ',\n',
  root: 'rgb(100%, 100%, 100%)'
}
```

### Actual Behavior

Commas are not added.

```js
{
  punctuation: ',\n',
  root: 'rgb(100% 100% 100%)'
}
```

**Comment by shellscape** [comment]
Very strange. We're not deviating or overwriting how PostCSS's nodes behave in that regard.

**Comment by jonathantneal** [comment]
The issue is that `Func` is stringified by its `params` and not by its `nodes`.

```js
astValue.nodes[0].params = 'NODES ARE IGNORED';

console.log({
	root: valuesParser.nodeToString(astValue) // "rgbNODES ARE IGNORED"
});
```

**Comment by shellscape** [comment]
Yeah, here's the culprit: https://github.com/shellscape/postcss-values-parser/blob/81069561428fdd5b29abfd8ad1a258687275487e/lib/ValuesStringifier.js#L28

**Comment by jonathantneal** [comment]
As you intend it, is `params` to be a sugary getter/setter (i.e. parse/nodeToString) of `nodes`, or should `params` be available at all?

**Comment by shellscape** [comment]
It was intended to give a snapshot of the function sans name. This was 100% a lack of foresight on my part. Currently working on a fix for that.
