### ISSUE TITLE
Node 11+ import support

### ISSUE THREAD

**Issue by jonathantneal** [shellscape/postcss-values-parser#70]
- Webpack Version: N/A
- Operating System (or Browser): N/A
- Node Version: v11.10.1 (and all versions yet supporting `import`/`export`)
- postcss-values-parser Version: 3.0.1

### How Do We Reproduce?

Import the `parse` function from an mjs file:

```
// test.mjs
import { parse } from 'postcss-values-parser';
```

Run the mjs file:

```
node --experimental-modules test.mjs
```

### Expected Behavior

The `parse` function is imported.

### Actual Behavior

Nothing is imported, because the package only exports CommonJS `modules.exports`, a technique allowable in Babel but not in Node.

A secondary mjs file would need to be created that correctly exported individual parts (like `export function parse() { [code] }`). This file would also need to be wired into `package.json` as `module` (beside `main`).

**Comment by shellscape** [comment]
_(Updated the issue title to more accurately reflect the crux of the issue)_

I currently have no desire to tailor a solution explicitly for a single Node version, and I don't want to wade into the `.mjs` mess. But I take the same position I did with TypeScript - if there's a non-invasive, minimal way to support it, I'll happily accept a PR to do so.

**Comment by jonathantneal** [comment]
I think you may have misunderstood that the README currently advertises functionality that does not work without a sugary Babel transformation. It is TypeScript and Babel that are the fun sugary things to support; Node is the actual thing to support. This bug is not specific to a particular Node version, but all Node versions supporting `import`/`export`, as I mentioned in the bug report. I believe this means the bug spans from Node 8 to Node 12.

I have created a PR for this @ https://github.com/shellscape/postcss-values-parser/pull/71

**Comment by shellscape** [comment]
> the README currently advertises functionality that does not work without a sugary Babel transformation

I would disagree there. The readme makes no mention of `import`, only CommonJS `require`. And in the case of `require` and CommonJS, it works as expected and documented. Leave it to the Node working group to introduce new pain 🙃

**Comment by jonathantneal** [comment]
I am mistaken and you are correct — it references `require`. I will close this issue.

**Comment by shellscape** [comment]
No worries. I'd still like to pursue your PR further, however.
