### ISSUE TITLE
Quarter Milimeters unit missing

### ISSUE THREAD

**Issue by AndyOGo** [shellscape/postcss-values-parser#80]
- Webpack Version: not used
- Operating System (or Browser): MacOS
- Node Version: `v10.15.0`
- postcss-values-parser Version: `3.0.2`

### How Do We Reproduce?

```css
.foo { margin: 10q; }
```

### Expected Behavior

Should be a valid absolute CSS unit.

https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Values_and_units
https://drafts.csswg.org/css-values-3/#absolute-lengths

### Actual Behavior

It's not valid.

**Comment by shellscape** [comment]
Awesome, thank you for the spec link. This project has really revealed how much about the CSS spec that I _don't_ know.

**Comment by AndyOGo** [comment]
Glad to help :)
I'm totally with you, writing parsers confronts one with all the nifty details of specs 😅 

This package is awesome, you are doing a fantastic job man.

**Comment by AndyOGo** [comment]
@shellscape 
Thanks for your super quick response.
I saw you even made a new release on github, but I can't get it from [npm](https://www.npmjs.com/package/postcss-values-parser).

May I ask you to publish it please?

**Comment by shellscape** [comment]
D'oh. Thanks for the heads up. Coming at you...
