### ISSUE TITLE
Depends on deprecated package "flatten"

### ISSUE THREAD

**Issue by austinbutler** [shellscape/postcss-values-parser#86]
### Expected Behavior / Situation

Installation does not install a deprecated package.

### Actual Behavior / Situation

Installation installs deprecated package "flatten."

```warning postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.```

### Modification Proposal

Remove dependency on flatten.

**Comment by shellscape** [comment]
Thanks for raising the issue. `flatten` is likely a dependency of another module. We don't use it directly, as can be seen here https://github.com/shellscape/postcss-values-parser/blob/dc43c80cd65c8aa7368faccbd9510bddf09e8811/package.json#L35-L41

**Comment by JoshRobertson** [comment]
flatten is/was a dependency of this package up until v 2.0.1. it looks like it was removed in v 3.0 but until downstream packages (about a dozen in my repo) update to use ^3.0, this error will show

**Comment by shellscape** [comment]
v3.0.4 went up the other day, and should resolve that downstream issue. If it doesn't, please contact the offending package's project.

**Comment by jaredbeck** [comment]
Can this fix easily be backported to the v2 series? Thanks!

**Comment by rmkanda** [comment]
Bumping up!!!
@shellscape Can this fix easily be backported to the v2 series? Thanks!

**Comment by shellscape** [comment]
I'm sorry but I don't have the bandwidth to backport features to old major versions. Please use the newer version. Thanks!
