### ISSUE TITLE
Flatten is deprecated

### ISSUE THREAD

**Issue by mrleblanc101** [shellscape/postcss-values-parser#88]
When installing Nuxt, i get an error that flatten is deprecated.
`warning nuxt > @nuxt/webpack > postcss-preset-env > postcss-color-functional-notation > postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.`

### Expected Behavior / Situation
Should not trigger warning

### Actual Behavior / Situation
Trigger warning

### Modification Proposal
Move away from this package. 
Maybe use Array.prototype.flat with babel to polyfill

**Comment by shellscape** [comment]
Thanks for the issue and your suggestion. We're aware the module has been deprecated. It's not seeing heavy use internally and so this module is not a top priority to replace. We'll likely clean this up in the next release.
