### ISSUE TITLE
Easy to backport removal of flatten?

### ISSUE THREAD

**Issue by jaredbeck** [shellscape/postcss-values-parser#90]
### Feature Use Case

To address the deprecation warning noted in #86, #88, the dependency on `flatten` was removed in v3. 

### Feature Proposal

Can the removal of `flatten` easily be backported to the v2 series? 

Consuming packages, like postcss-color-functional-notation are [having a hard time](https://github.com/jonathantneal/postcss-color-functional-notation/issues/3) upgrading to v3.

**Comment by shellscape** [comment]
I've already addressed and denied this request in #86. v3 has been stable for some time now. Consumers will have to use that version, or you'll have to live with a deprecation notice in your console (which is an extremely minor inconvenience at worst). Please direct your energies and efforts to helping that project update to v3
